### ISSUE TITLE
Needed packages are not available anymore during installation 

### ISSUE THREAD

**Issue by KroPIixx** [firien/duplo-train#1]
It seems that several needed packages are not available anymore during installation. At the end the Server could not be started. I would like to setup such a train server, but I wasn't able to fix this issue - can someone help?

**Comment by firien** [comment]
I haven't booted this up in a while. did you try the newer [`node-16-update`](https://github.com/firien/duplo-train/tree/node-16-update) branch?

**Comment by KroPIixx** [comment]
Yes, now I have tried nearly every possible combination. Errors always occur during installation and certain packages cannot be found on GitHub.

**Comment by firien** [comment]
can you post your errors? and what system you are on?

----

I did a fresh clone of repo (on macOS 14.2.1, node v18.12.1) and was able to 

- `npm install`
- `node server.js`

without any issues on both main & [`node-16-update`](https://github.com/firien/duplo-train/tree/node-16-update) branch.

**Comment by firien** [comment]
[`node-20-update`](https://github.com/firien/duplo-train/tree/node-20-update) has added [@abandonware/bluetooth-hci-socket](https://www.npmjs.com/package/@abandonware/bluetooth-hci-socket) dependency.

see: https://github.com/nathankellenicki/node-poweredup/issues/176

`node-20-update` branch currently defaults to port `3020`, I will switch it back to port `3000` when merged.

----

FYI - I did just boot this up on a fresh new pi zero 2 W

**Comment by KroPIixx** [comment]
hi, I bought a new Pi Zero 2 W and got it running with Node 16.  I think the problem is with the first generation PI Zero. Thank you!

**Comment by firien** [comment]
good to hear. But fyi this is more unstable than before. I ran this on node 8 on original pi zero for years without issue. It is crashing frequently now.

**Comment by firien** [comment]
I tagged the old stable node 8 code, if you want to try that on old pi zero w
https://github.com/firien/duplo-train/releases/tag/pi-zero-w-node-8
